### ISSUE TITLE
Implement a Pull Request Template with Checklist for Code Checks and Issue Linking

### ISSUE THREAD

**Issue by abeltavares** [ArvindParekh/Lofi-Music-App#21]
Want to standardize pull requests and ensure that they meet the project's contribution guidelines, so I propose implementing a pull request template. 

The proposed PR template will include the **following key items**:

Link to Issue: Ensure contributors explicitly link PRs to corresponding issues using the closes #issue_number syntax, making it easier to track and automate closure of issues when PRs are merged.

**Code Checks**: Include a checkbox to confirm that all code checks have passed. This is relevant as we plan to implement pre-commit hooks using Prettier for style checks, ensuring that all submitted code is accordingly to our formatting standards.

Testing: Confirm that new code contributions have adequate tests and that all tests pass.

**Implementation**:

**Create the PR Template**: Add a `PULL_REQUEST_TEMPLATE.md` file in the .github directory with the proposed checklist.

We can open a discussion bellow in the comments to finalize the checklist items with input from maintainers and active contributors.

**Comment by abeltavares** [comment]
@ArvindParekh seems good for you that template?

**Comment by ArvindParekh** [comment]
Thanks for raising @abeltavares! I think this looks good!

- The code check currently just includes conforming with the project's coding style, which is managed by Prettier. Perhaps we should phrase it as "My changes follow the coding style of the project".
- Since tests have not been set up yet, we can consider omitting them from the template for now and incorporating them later when they are established.
- Additionally, I suggest adding one more check: "The PR title provides a concise description of my changes".

What do you think?

**Comment by abeltavares** [comment]
> Thanks for raising @abeltavares! I think this looks good!
> 
> * The code check currently just includes conforming with the project's coding style, which is managed by Prettier. Perhaps we should phrase it as "My changes follow the coding style of the project".
> * Since tests have not been set up yet, we can consider omitting them from the template for now and incorporating them later when they are established.
> * Additionally, I suggest adding one more check: "The PR title provides a concise description of my changes".
> 
> What do you think?

seems good, the update (with tests check) is done later then with the integration of the tests

- [ ] The PR title provides a concise description of my changes
- [ ] My changes follow the coding style of the project
- [ ] Closes #xxxx (Replace xxxx with the GitHub issue number)

**Comment by ArvindParekh** [comment]
Perfect, looks great! 👍🏻 
I think that once Prettier is added to the project, we should also add that to the CONTRIBUTING.md documentation, saying that we use Prettier to handle the coding style of the project, so make sure the changes are in accordance with that before raising a PR.

**Comment by webbrain-one** [comment]
Hi! 👋 I’ve opened a PR to address this: https://github.com/ArvindParekh/Lofi-Music-App/pull/32

This implements the requested PR template by adding a `PULL_REQUEST_TEMPLATE.md` file in the `.github` directory. It includes the checklist items you suggested for linking/closing issues, confirming tests pass, and verifying code checks. Let me know if you’d like any tweaks to the wording or format! Thanks! 🚀
